---
title: "Patterns in Support for Reparations - Survey Analysis"
output: html_document
---

<style type="text/css">

h1 {
  text-align: center;
  font-weight: bold;
  font-family: 'Helvetica Neue';
}

h2 {
 font-family: 'Helvetica Neue';
}

body{
 font-family: 'Helvetica Neue';
 font-size: 16px;
}

</style>

<br>
<br>



```{r setup, include=FALSE}
# for many data tricks!
library(tidyverse)
# for a few handy personal functions
library(willbprocessed)
# easy calculations on survey data
library(srvyr)
# for pretty tables
library(kableExtra)
# for paths
library(here)
# color palletes
library(viridis)

```


```{r colors, include=FALSE}
# Colors for plots
# same colors as first post for consistency
v_pal <- viridis::viridis(5)
v_pal8 <- viridis::viridis(8)
# new colors for reparations support
magma_pal6 <- viridis::magma(6)
magma_pal4 <- viridis::magma(4)
# creating smaller palletes from those ^
# generations plots
gen3_colors <- c(v_pal[3], v_pal[2], v_pal[1])
gen6_colors <- c(v_pal8[6], v_pal8[5], v_pal8[4], v_pal8[3], v_pal8[2], v_pal8[1])
# reparations plots
rep5_colors <- c(magma_pal6[2],magma_pal6[3], magma_pal6[6], magma_pal6[5], magma_pal6[4])
rep3_colors <- c(magma_pal4[2], magma_pal4[4], magma_pal4[3])


```

```{r functions, include=FALSE}
# the font for this post
post_font <- "Helvetica Neue"

# decreasing copy-paste for similar pies
one_var_pie <- function(df, varname, color_pal){
  ggplot(data = df, aes(x="", fill = .data[[varname]], y = pct)) + 
  geom_bar(stat = "identity", color = "black") +
  geom_text(
    aes(label = Percent, x = 1.6, y = pct),
    size = 5,
    position = position_stack(vjust = 0.5),
    fontface = "bold",
    color = "black") +
  # to make it pie chart
  coord_polar(theta = "y") +
  scale_fill_manual(values = color_pal) +
  # no axes
  theme_void() +
  theme(legend.position = "right",
        legend.title = element_blank(),
        plot.title = element_text(size = 20, hjust = 0.5, face = "bold"),
        text = element_text(family = post_font))
  
}
# THIS IS GOOD, IMPLIMENT TIME
format_plot_data <- function(df, dummies, varname, var_levels, group_vars = c()){
  df %>%
    # select only cols we need, if no group_vars provided it will just do id and weight
    select(all_of(c("respondent_id", "weight", group_vars))) %>%
    bind_cols(dummies) %>%
    pivot_longer(
      # patterns based on our use cases. not robust lol
      cols = matches(" |Support|Oppose|Agree|Disagree"),
      names_to = varname,
      values_to = "value") %>%
    # levels so right orders in plots
    mutate(!!varname := factor(.data[[varname]], levels = var_levels)) %>%
    # thanks for making this easy srvyr!
    srvyr::as_survey(weights = weight, ids = respondent_id) %>%
    srvyr::group_by_at(c(group_vars, varname)) %>%
    srvyr::summarise(pct = survey_mean(value, vartype = "ci", na.rm = T)) %>%
  mutate(
    # round * 100
    across(all_of(contains("pct")), willbprocessed::as_percent, 1, F),
    # for labels
    Percent = paste0(pct, "%"),
  )
}

# creating table's for reparations breakdown
hr40_tabs <- function(srvyr_df){
  srvyr_df %>%
  srvyr::summarise(
    Yes = survey_mean(I(aware_hr40 == "Yes"), vartype = "ci", na.rm = T),
    No = survey_mean(I(aware_hr40 == "No"), vartype = "ci", na.rm = T)
    ) %>%
    #for now cuz such big error bars
    mutate(across(all_of(matches("Yes|No")), as_percent, 1, T)) %>% 
    select(-all_of(matches("upp|low")))
}


```


```{r clean_dataset, include=FALSE}
# data is not public
df <- readRDS(here("Not For Git/Clean_Data/ras_20210615.RDS")) %>%
  mutate(
    # the weight for this dataset
    weight = weight_rep_unique,
    # going from 5 categories to 3
    reparations3 = str_extract(reparations,"support|oppose|Not sure") %>% str_to_sentence() %>%
      factor(levels = c("Support", "Oppose", "Not sure")),
    # generations 3 cat
    generations3 = 
      recode(as.character(generations), "Strongly agree" = "Agree", "Somewhat agree" = "Agree", 
                        "Neither agree nor disagree" = "Other", "Somewhat disagree" = "Disagree", 
                        "Strongly disagree" = "Disagree", 
                        "Prefer not to say" = "Other") %>%
      factor(levels = c("Agree", "Other", "Disagree"))
  ) %>%
  # NAs are those that do not have responses to reparations question
  filter(!is.na(weight))
# dummies for what level people support reparations
rep_dummies <- factor_to_dummies(df$reparations)
# dummies for what support, oppose, not sure
rep3_dummies <- factor_to_dummies(df$reparations3)
# dummies for generations categories
gen_dummies <- factor_to_dummies(df$generations)

# srvyr version of the df
srvyr_df <-  srvyr::as_survey(df, weights = weight, ids = respondent_id)

```

## Half of Americans Are Open To Reparations

```{r reparations_processing, include=FALSE}

reparations_breakdown <- format_plot_data(
  df, 
  dummies = rep_dummies,
  varname = "reparations",
  var_levels = c("Strongly support", "Somewhat support", "Not sure",
    "Somewhat oppose", "Strongly oppose")
  ) %>%
  mutate(
    Percent = Percent %>%
      # maybe make this as feature of the as percent fxn...
      recode("16%" = "16.0%")
  )


```

```{r reparations_pie, echo=F, fig.width=10, fig.height=7.5, message=F}

one_var_pie(reparations_breakdown, 'reparations', rep5_colors) +
  labs(title = "Support for Reparations", x = "", y = "")

```

```{r rep3_race3_processing, include = FALSE}
# format the data. similar to above. should probs fxn this
rep3_race3 <-format_plot_data(
  df, 
  dummies = rep3_dummies,
  varname = "reparations",
  var_levels = c("Not sure", "Oppose", "Support"),
  group_vars = "race4"
  ) %>%
  # error bars are pretty huge
  filter(race4 != "Other") %>%
  # just so things make a little more sense
  rename("race3" = "race4")


```


```{r rep3_race3_bar, fig.width=10, fig.height=7.5, echo=FALSE}
ggplot(data = rep3_race3) +
  # the parameters for the bar plot
  geom_bar(
    aes(x = race3, y = pct, fill = reparations),
    color = "black",
    stat = "identity",
    position = position_dodge(width = 0.9)
    ) +
  # making it width wise
  coord_flip() +
  # the paramters for the text
  geom_text(
    # if I want to put it at the end
    # aes(x = race3, y = pct + 5, label = Percent, group = reparations),
    aes(x = race3, y = (pct/2), label = Percent, group = reparations),
    #position = position_stack(vjust = 0.5),
    position = position_dodge(width = 0.9),
    color = "black",
    fontface = "bold",
 
  ) +
  # now the error bars
  geom_errorbar(
    aes(x = race3, ymin = pct_low, ymax = pct_upp, group = reparations),
    width = 0.2,
    position = position_dodge(width = 0.9)
    ) +
  # colors for the bars
  scale_fill_manual(values = rep3_colors,  breaks = c("Support", "Not sure","Oppose")) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  # theme
  theme_minimal() +
  theme(legend.position = "top",
        legend.title = element_blank(),
        plot.title = element_text(size = 20, hjust = 0.5, face = "bold"),
        axis.text.x= element_blank(),
        text = element_text(family = "Helvetica Neue")) +
  labs(title = "Reparations Support by Race", x = "", y = "")

# let's play with plotly displays perhaps
# if i wanna use plotly... it's take more than this
# plotly::ggplotly(tmp)

```

```{r include=FALSE, generations_processing}

generations_breakdown <- format_plot_data(
  df, 
  dummies = gen_dummies,
  varname = "generations",
  var_levels = 
    c("Strongly agree", "Somewhat agree", "Prefer not to say",
      "Neither agree nor disagree", "Somewhat disagree", "Strongly disagree")
  ) 


```

```{r generations_pie, echo=F, fig.width=10, fig.height=7.5, message=F}

one_var_pie(generations_breakdown, 'generations', gen6_colors) +
  labs(title = "Agreement with Generations Statement", x = "", y = "")

```

```{r include=FALSE}

gen3_rep3 <- format_plot_data(
  df, 
  dummies = rep3_dummies,
  varname = "reparations",
  var_levels = c("Not sure", "Oppose", "Support"),
  group_vars = "generations3"
  ) %>%
  mutate(
    reparations = factor(as.character(reparations), levels = c("Support", "Not sure", "Oppose")),
    pct_label = round(pct),
    #for better spacing in plot labels
    pct_label = paste0("   ", pct_label, "%")
  )


```

```{r echo=F, fig.width=10, fig.height=7.5, message=F}


ggplot(data = gen3_rep3) +
  geom_bar(stat = "identity", aes(x = reparations, y = pct, fill = generations3),
           position = "dodge") +
  scale_fill_manual(values = gen3_colors) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  geom_errorbar(aes(x = reparations, ymin = pct_low, ymax = pct_upp, group = generations3),
                width = 0.2, position = position_dodge(width = 0.9)) +
  geom_text(
    aes(x = reparations, y = pct_upp + 5, label = pct_label, group = generations3),
    position = position_dodge(width = 0.9),
    size = 5,
    fontface = "bold",
    color = "black"
    ) +
  theme_minimal() +
  theme(legend.position = "top",
        legend.title = element_blank(),
        plot.title = element_text(size = 20, hjust = 0.5, face = "bold"),
        text = element_text(family = "Helvetica Neue")) +
  labs(title = "Support for Reparations By Generations Statement", x = "", y = "")


```


```{r hr40_table, echo=FALSE}
# first broken down by reparations support
hr40_bkdwn <- srvyr::group_by(srvyr_df, reparations3) %>%
  hr40_tabs() %>%
  rename("Support for Reparations" = reparations3)
# then overall
hr40_all <- hr40_tabs(srvyr_df) %>%
  mutate(`Support for Reparations` = "All")

# and then together as one html table
hr40_bkdwn %>%
  bind_rows(hr40_all) %>%
  kableExtra::kable(
    caption = "<center><strong>Awareness of HR40 by Support for Reparations</strong></center>",
    align = c("l", "c", "c"),
    table.attr = "style='width:70%;'"
    ) %>%
  add_header_above(c(" " = 1, "Aware of HR40" = 2)) %>%
  kableExtra::kable_paper(html_font = "Helvetica Neue")

```

